### ISSUE TITLE
Impossible to get a 404 response

### ISSUE THREAD

**Issue by jakzal** [vlingo/vlingo-helloworld#2]
The code in `GreetingResource` suggests that in some cases there should be a 404 response returned, i.e. if the greeting is not found:

```java
  public Completes<Response> queryGreeting(String greetingId) {
    return queries.greetingOf(greetingId)
            .andThenTo(data -> Completes.withSuccess(Response.of(Ok, serialized(data))))
            .otherwise(noData -> Response.of(NotFound, greetingLocation(greetingId)));
  }
```

However, that is not what happens. When we ask for a missing greeting, a new (empty) one is returned:

```http
$ http GET 'http://localhost:18080/greetings/240'
HTTP/1.1 200 OK
Content-Length: 91

{"id":"","message":"","messageChangedCount":0,"description":"","descriptionChangedCount":0}
```

A request to PATCH a missing resource hangs forever:

```
$ http PATCH 'http://localhost:18080/greetings/240/description' value=desc1

```

While in logs we can see:

```
16:27:09.531 [pool-2-thread-3] ERROR io.vlingo.actors.Logger - io.vlingo.actors.plugin.supervision.DefaultSupervisorOverride - DefaultSupervisorOverride: Failure of: Address[id=240, name=(none)] because: io.vlingo.wire.channel.SocketChannelSelectionProcessorActor cannot be cast to io.vlingo.hello.model.Greeting Action: Resuming.
java.lang.ClassCastException: io.vlingo.wire.channel.SocketChannelSelectionProcessorActor cannot be cast to io.vlingo.hello.model.Greeting
	at io.vlingo.actors.LocalMessage.internalDeliver(LocalMessage.java:121) ~[vlingo-actors-1.2.8.jar:na]
	at io.vlingo.actors.LocalMessage.deliver(LocalMessage.java:53) ~[vlingo-actors-1.2.8.jar:na]
	at io.vlingo.actors.plugin.mailbox.concurrentqueue.ConcurrentQueueMailbox.run(ConcurrentQueueMailbox.java:108) ~[vlingo-actors-1.2.8.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92]
16:27:09.532 [pool-2-thread-5] ERROR io.vlingo.actors.Logger - io.vlingo.wire.fdx.bidirectional.ServerRequestResponseChannelActor - io.vlingo.wire.channel.SocketChannelSelectionProcessorActor - Default before resume recovery after: io.vlingo.wire.channel.SocketChannelSelectionProcessorActor cannot be cast to io.vlingo.hello.model.Greeting
java.lang.ClassCastException: io.vlingo.wire.channel.SocketChannelSelectionProcessorActor cannot be cast to io.vlingo.hello.model.Greeting
	at io.vlingo.actors.LocalMessage.internalDeliver(LocalMessage.java:121) ~[vlingo-actors-1.2.8.jar:na]
	at io.vlingo.actors.LocalMessage.deliver(LocalMessage.java:53) ~[vlingo-actors-1.2.8.jar:na]
	at io.vlingo.actors.plugin.mailbox.concurrentqueue.ConcurrentQueueMailbox.run(ConcurrentQueueMailbox.java:108) ~[vlingo-actors-1.2.8.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92]
```

**Comment by VaughnVernon** [comment]
Fixed by https://github.com/vlingo/vlingo-common/issues/12
